In [5]:
import pandas as pd
import os

from datetime import datetime, timedelta

import eikon as ek

## Import Data

Import to remember to set your api_key in the code

In [6]:
# Creating Class to Import Data

class ImportData:
 
    def __init__(self, filename = None):
        
        # Constants as instance attributes
        self.end_date = datetime.today()
        self.start_date = self.end_date - timedelta(days=7*365)
        self.filename = filename

        self.export_folder = "../../data/processed"
        self.raw_folder = "../../data/raw"

        os.makedirs(self.export_folder, exist_ok=True)
    
    # Import Data

    def import_eikon_series(self, ticker_code: str, app_key):
        
        # Ensure valid API key
        ek.set_app_key(app_key)  # Make sure to use a valid API key
        
        # Fetch data from Eikon
        df = ek.get_timeseries([ticker_code], 
                               start_date=self.start_date, 
                               end_date=self.end_date)

        # Reset index to make the date a column
        df.reset_index(inplace=True)

        # Rename columns for clarity
        df.columns = ['Date', ticker_code]

        filepath = os.path.join(self.export_folder, f"{self.filename}.csv")
        df.to_csv(filepath, index=False)
        print(f"Data exported to {filepath}")
    
        return df
    
    def import_eia_raw_data(self, sheet_name, col_position):

        # Listar arquivos disponíveis no diretório
        files = os.listdir(self.raw_folder)
        if not files:
            raise FileNotFoundError(f"Nenhum arquivo encontrado em {self.raw_folder}")

        # Seleciona o primeiro arquivo encontrado (ajuste conforme necessário)
        file_import_name = files[0]  
        file_path_import = os.path.join(self.raw_folder, file_import_name)

        # Importar o arquivo Excel
        df = pd.read_excel(file_path_import, sheet_name=sheet_name, usecols=col_position, skiprows= 2)

        filepath = os.path.join(self.export_folder, f"{self.filename}.csv")
        df.to_csv(filepath, index=False)
        print(f"Data exported to {filepath}")

        return df

In [7]:
# Stocks
ImportData("us_gasoline_stocks").import_eia_raw_data("Data 3", [0, 1])
ImportData("padd1_gasoline_stocks").import_eia_raw_data("Data 3", [0, 2])
ImportData("padd2_gasoline_stocks").import_eia_raw_data("Data 3", [0, 3])
ImportData("padd3_gasoline_stocks").import_eia_raw_data("Data 3", [0, 4])
ImportData("padd4&5_gasoline_stocks").import_eia_raw_data("Data 3", [0, 5, 6])

Data exported to ../../data/processed/us_gasoline_stocks.csv
Data exported to ../../data/processed/padd1_gasoline_stocks.csv
Data exported to ../../data/processed/padd2_gasoline_stocks.csv
Data exported to ../../data/processed/padd3_gasoline_stocks.csv
Data exported to ../../data/processed/padd4&5_gasoline_stocks.csv

,Date,Weekly Rocky Mountain (PADD 4) Ending Stocks of Total Gasoline (Thousand Barrels),Weekly West Coast (PADD 5) Ending Stocks of Total Gasoline (Thousand Barrels)
0,1983-01-07,NaN,NaN
1,1983-01-14,NaN,NaN
2,1983-01-21,NaN,NaN
3,1983-01-28,NaN,NaN
4,1983-02-04,NaN,NaN
...,...,...,...
2189,2025-01-24,8639.0,30386.0
2190,2025-01-31,8659.0,30129.0
2191,2025-02-07,8837.0,28766.0
2192,2025-02-14,9083.0,28589.0
2193,2025-02-21,9095.0,29363.0

In [ ]:
# Demand
ImportData("us_gasoline_demand").import_eia_raw_data("Data 10", [0, 1])

Data exported to ../../data/processed/us_gasoline_demand.csv

,Date,Weekly U.S. Product Supplied of Finished Motor Gasoline (Thousand Barrels per Day)
0,1991-02-08,6621
1,1991-02-15,6433
2,1991-02-22,6582
3,1991-03-01,7224
4,1991-03-08,6875
...,...,...
1772,2025-01-24,8302
1773,2025-01-31,8328
1774,2025-02-07,8576
1775,2025-02-14,8239
1776,2025-02-21,8454